FROM python:alpine

COPY ./requirements.txt /

RUN set -ex && \
 apk add --no-cache --virtual .build-deps build-base openssl-dev python3-dev && \
 pip install -r /requirements.txt && \
 apk del .build-deps

COPY ./app.py / 

ENTRYPOINT python3 /app.py
