all: basic multistage small

basic:
	docker build -f Dockerfile.basic -t demo_basic .

multistage:
	docker build -f Dockerfile.multistage -t demo_multistage .

small:
	docker build -f Dockerfile.small -t demo_small .
